# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    images_categories_directory: '%kernel.project_dir%/web/images/categories'

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    SoulFamily\BestEntityBundle\:
        resource: '../../src/SoulFamily/BestEntityBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/SoulFamily/BestEntityBundle/{Entity,Repository,Tests}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    SoulFamily\BestEntityBundle\Controller\:
        resource: '../../src/SoulFamily/BestEntityBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    _soulfamily.upload_external_file:
        class: SoulFamily\BestEntityBundle\Service\UploadExternalFile
        arguments: ['%kernel.project_dir%/web/images/categories']
        public: true

    _soulfamily.crawler:
        class: SoulFamily\BestEntityBundle\Service\CrawlCategories
        public: true
