<?php

namespace SoulFamily\BestEntityBundle\Repository;

/**
 * EntityDescriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityDescriptionRepository extends \Doctrine\ORM\EntityRepository
{

    public function deleteByCategory($category)
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery(
            'DELETE FROM SoulFamilyBestEntityBundle:EntityDescription e ' .
            'WHERE e.category = :CATEGORY_ID '
        );

        $query->setParameter('CATEGORY_ID', $category->getId());
        return $query->execute();

    }
}
