<?php

namespace SoulFamily\BestEntityBundle\Repository;

/**
 * EntityDescriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityDescriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
