<?php

namespace SoulFamily\BestEntityBundle\Repository;

/**
 * List_EntitiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class List_EntitiesRepository extends \Doctrine\ORM\EntityRepository
{
}
