<?php

namespace SoulFamily\BestEntityBundle\Repository;

/**
 * User_EntityListsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class User_EntityListsRepository extends \Doctrine\ORM\EntityRepository
{
}
